version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/database/jobberwocky.db
    working_dir: /var/www/html

  jobberwocky-extra-source:
    image: node:18-alpine
    ports:
      - "3001:3001"
    volumes:
      - ./external-source:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    environment:
      - PORT=3001

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port

